### **1. Trasformare cicli in list comprehension**

Fai tre esempi di cicli producono una lista e poi riscrivi lo stesso codice usando la list comprehension

In [1]:
numeri=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

quadrati=[]
for n in numeri:
    quadrati.append(n**2)
quadrati=[n**2 for n in numeri]                             # list comprehension
print(quadrati)

pari=[]
for n in numeri:
    if n%2==0:
        pari.append(n)
pari=[n for n in numeri if n%2==0]                          # list comprehension
print(pari)

prodotti_sopra_50=[]
for n in range(10):
    if n*(n+1)>50:
        prodotti_sopra_50.append(n)
prodotti_sopra_50=[n for n in range(10) if n*(n+1)>50]      # list comprehension
print(prodotti_sopra_50)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[0, 2, 4, 6, 8]
[7, 8, 9]


### **2. Vettore di Numeri Primi**

1. **Crea un vettore** contenente tutti i numeri primi compresi tra **0 e 10**  
   _(Puoi scriverli direttamente nell'array)._

2. **Conta quanti numeri ci sono nel vettore** utilizzando la funzione `len()`.  **Ottieni lo stesso numero** accedendo all'attributo `.size` del vettore.

3. Quale pensi sia il tipo di dato (`dtype`) del vettore?  Prova a rispondere senza eseguire il codice e Verifica la tua risposta accedendo all'attributo `.dtype` del vettore

4. Scrivi l'array usando una list comprehension che controlla che i numeri siano primi. 

In [2]:
import numpy as np
vettore_primi=np.array([2, 3, 5, 7])
lunghezza_vettore1=len(vettore_primi)
lunghezza_vettore2=vettore_primi.size
print(f"Il tipo di dato (dtype) è: {vettore_primi.dtype}")
primi_compresi = np.array([n for n in range(2, 11) if all(n%i!=0 for i in range(2, int(n**0.5)+1))])
print(lunghezza_vettore1)
print(lunghezza_vettore2)
print(primi_compresi)

Il tipo di dato (dtype) è: int64
4
4
[2 3 5 7]


### **3.  Operazioni su array**
Crea un array **a**, 1D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente una sottostringa a piacere e **c** che è il reverse dell'array **a** (esempio [1,2,3] diventa [3,2,1]) .  Dividi l'array **a** per l'array **c**. Fai la stessa cosa per una lista.

In [3]:
import numpy as np
a=np.arange(1, 11)
b1=a[2:6]
b2=a[4:8]
c=a[::-1]
divisione_array=a/c

lista_a=list(range(1, 11))
lista_b1=lista_a[2:6]
lista_b2=lista_a[4:8]
lista_c=lista_a[::-1]
divisione_lista=[]
for x, y in zip(lista_a, lista_c):
    divisione_lista.append(x/y)
print(a)
print(b1)
print(b2)
print(c)
print(divisione_array)
print(lista_a)
print(lista_b1)
print(lista_b2)
print(lista_c)
print(divisione_lista)

[ 1  2  3  4  5  6  7  8  9 10]
[3 4 5 6]
[5 6 7 8]
[10  9  8  7  6  5  4  3  2  1]
[ 0.1         0.22222222  0.375       0.57142857  0.83333333  1.2
  1.75        2.66666667  4.5        10.        ]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[3, 4, 5, 6]
[5, 6, 7, 8]
[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
[0.1, 0.2222222222222222, 0.375, 0.5714285714285714, 0.8333333333333334, 1.2, 1.75, 2.6666666666666665, 4.5, 10.0]
